// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import environment from '@/lib/environment';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: environment.DATABASE_URL,
  },
});
